#!/usr/bin/env bash
set -euo pipefail

# Template: run GWAS logistic regression for 3 contrasts
#
# Required:
#   - QC-passed PLINK prefix: --bfile <PREFIX>
#   - phenotype and covariate files generated by prepare_pheno_covar.py
#
# Example:
#   bash scripts/gwas/run_gwas_plink.sh \
#     --plink plink \
#     --bfile ADNI_Final_hg19_filtered \
#     --pheno-dir outputs/gwas/pheno_covar \
#     --out-dir outputs/gwas/assoc

usage() {
  echo "Usage: run_gwas_plink.sh --bfile PREFIX --pheno-dir DIR --out-dir DIR [--plink plink]"
  exit 2
}

PLINK="plink"
BFILE=""
PHENO_DIR=""
OUT_DIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --plink) PLINK="$2"; shift 2 ;;
    --bfile) BFILE="$2"; shift 2 ;;
    --pheno-dir) PHENO_DIR="$2"; shift 2 ;;
    --out-dir) OUT_DIR="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) echo "[ERROR] Unknown arg: $1"; usage ;;
  esac
done

if [[ -z "$BFILE" || -z "$PHENO_DIR" || -z "$OUT_DIR" ]]; then
  usage
fi

mkdir -p "$OUT_DIR"

declare -a TAGS=("AsymAD_vs_Control" "AsymAD_vs_TypAD" "TypAD_vs_Control")

for TAG in "${TAGS[@]}"; do
  PHENO="$PHENO_DIR/pheno_${TAG}.txt"
  COVAR="$PHENO_DIR/covar_${TAG}.txt"

  if [[ ! -f "$PHENO" || ! -f "$COVAR" ]]; then
    echo "[WARN] Missing files for $TAG. Expected:"
    echo "  $PHENO"
    echo "  $COVAR"
    continue
  fi

  echo "[INFO] Running GWAS: $TAG"
  "$PLINK" \
    --bfile "$BFILE" \
    --logistic \
    --pheno "$PHENO" \
    --covar "$COVAR" \
    --allow-no-sex \
    --out "$OUT_DIR/gwas_${TAG}"
done
