#!/usr/bin/env python3
"""
ANMerge B2 Option-B with per-gene FDR across regions
===================================================

Model (per contrast, per gene, per region):
  MRI_region ~ Expr_gene + C(Group) + Expr_gene:C(Group) + Age + C(Sex) + C(Site)

Key output:
  q_within_gene = BH-FDR across all regions tested for that gene (per contrast)

INPUTS (already generated by your prep):
  results_b2/prepared_expr_mri_merged_with_selected_genes_AsymAD_vs_TypAD.csv
  results_b2/prepared_expr_mri_merged_with_selected_genes_AsymAD_vs_Control.csv
  results_b2/prepared_expr_mri_merged_with_selected_genes_TypAD_vs_Control.csv

OUTPUTS (NEW folder default: results_b2_optionB_pergeneFDR/):
  b2_pergene_<TAG>_all.csv
  b2_pergene_<TAG>_significant_qgene{thr}.csv
  b2_pergene_<TAG>_per_gene_summary.csv

Run:
  pip install statsmodels
  python anmerge_b2_optionB_pergeneFDR.py --data-dir .
"""

import argparse
from pathlib import Path
import numpy as np
import pandas as pd

import statsmodels.formula.api as smf
from statsmodels.stats.multitest import multipletests


def Qcol(name: str) -> str:
    name = str(name).replace('"', '\\"')
    return f'Q("{name}")'


def infer_groups(tag: str):
    t = tag.upper()
    if "ASYMAD" in t and "TYPAD" in t:
        return "Asym AD", "Typical AD"
    if "ASYMAD" in t and "CONTROL" in t:
        return "Asym AD", "Control"
    if "TYPAD" in t and "CONTROL" in t:
        return "Typical AD", "Control"
    raise ValueError(f"Cannot infer groups from tag: {tag}")


def clean_required_cols(df: pd.DataFrame):
    for req in ["Age", "Sex", "Site", "Subtype"]:
        if req not in df.columns:
            raise ValueError(f"Missing required column: {req}")
    df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
    df["Sex"] = df["Sex"].astype(str).str.strip()
    df["Site"] = df["Site"].astype(str).str.strip()
    df["Subtype"] = df["Subtype"].astype(str).str.strip()
    return df


def pick_mri_columns_auto(df: pd.DataFrame, min_nonnull: int):
    """
    Auto-detect MRI region columns.
    Prefer FS-like (lh_/rh_, lh./rh.). If too few, fallback to all numeric columns
    excluding known non-MRI columns.
    """
    pref = [c for c in df.columns if c.startswith("lh_") or c.startswith("rh_") or c.startswith("lh.") or c.startswith("rh.")]
    pref_good = []
    for c in pref:
        s = pd.to_numeric(df[c], errors="coerce")
        if s.notna().sum() >= min_nonnull and s.nunique(dropna=True) >= 5:
            pref_good.append(c)
    if len(pref_good) >= 10:
        return pref_good, "prefix(lh/rh)"

    exclude_exact = {"Age", "Subtype", "Group", "Sex", "Site", "RID", "ID", "SUBJ", "Subject", "subject"}
    def excluded(c: str) -> bool:
        if c in exclude_exact: return True
        if c.startswith("EXPR_"): return True
        return False

    numeric_cols = []
    for c in df.columns:
        if excluded(c):
            continue
        s = pd.to_numeric(df[c], errors="coerce")
        if s.notna().sum() >= min_nonnull and s.nunique(dropna=True) >= 5:
            numeric_cols.append(c)
    return numeric_cols, "all_numeric(fallback)"


def run_contrast(df: pd.DataFrame, tag: str, out_dir: Path,
                 min_per_group: int, min_total: int, min_nonnull_region: int,
                 cov_type: str, q_gene_thr: float):

    gA, gB = infer_groups(tag)
    df = clean_required_cols(df)
    df = df[df["Subtype"].isin([gA, gB])].copy()
    df["Group"] = pd.Categorical(df["Subtype"], categories=[gA, gB], ordered=True)

    nA = int((df["Group"] == gA).sum())
    nB = int((df["Group"] == gB).sum())

    gene_cols = [c for c in df.columns if c.startswith("EXPR_")]
    mri_cols, mode = pick_mri_columns_auto(df, min_nonnull=min_nonnull_region)

    print(f"[INFO] {tag}: N={len(df)} (A={gA}:{nA}, B={gB}:{nB}) | genes={len(gene_cols)} | regions={len(mri_cols)} [{mode}]")

    if nA < min_per_group or nB < min_per_group or not gene_cols or not mri_cols:
        print(f"[WARN] {tag}: insufficient data (groups/genes/regions). Skipping.")
        return

    cov_rhs = "Age + C(Sex) + C(Site)"
    rows = []

    for gcol in gene_cols:
        g = pd.to_numeric(df[gcol], errors="coerce")
        if g.notna().sum() < min_total or g.nunique(dropna=True) < 5:
            continue

        rhs = f'{Qcol(gcol)} + C(Group) + {Qcol(gcol)}:C(Group) + {cov_rhs}'
        int1 = f'{Qcol(gcol)}:C(Group)[T.{gB}]'
        int2 = f'C(Group)[T.{gB}]:{Qcol(gcol)}'

        for y in mri_cols:
            tmp = df[[y, gcol, "Group", "Age", "Sex", "Site"]].copy()
            tmp[y] = pd.to_numeric(tmp[y], errors="coerce")
            tmp[gcol] = pd.to_numeric(tmp[gcol], errors="coerce")
            tmp = tmp.replace([np.inf, -np.inf], np.nan).dropna()

            if len(tmp) < min_total:
                continue
            if (tmp["Group"] == gA).sum() < min_per_group or (tmp["Group"] == gB).sum() < min_per_group:
                continue
            if tmp[y].nunique(dropna=True) < 5:
                continue

            formula = f'{Qcol(y)} ~ {rhs}'
            try:
                fit = smf.ols(formula, data=tmp).fit(cov_type=cov_type)
            except Exception:
                continue

            if int1 in fit.params:
                b_int = fit.params.get(int1, np.nan)
                p_int = fit.pvalues.get(int1, np.nan)
            else:
                b_int = fit.params.get(int2, np.nan)
                p_int = fit.pvalues.get(int2, np.nan)

            rows.append({
                "contrast": tag,
                "gene": gcol.replace("EXPR_", ""),
                "region": y,
                "beta_interaction": b_int,
                "p_interaction": p_int,
                "r2": float(fit.rsquared),
                "N": int(fit.nobs),
            })

    if not rows:
        print(f"[WARN] {tag}: no models fit (after filtering).")
        return

    res = pd.DataFrame(rows)

    # ---- Per-gene BH-FDR across regions for that gene (this is what you want) ----
    res["q_within_gene"] = np.nan
    for gene, idx in res.groupby("gene").groups.items():
        p = res.loc[idx, "p_interaction"].to_numpy()
        ok = np.isfinite(p)
        q = np.full_like(p, np.nan, dtype=float)
        if ok.sum() > 0:
            q[ok] = multipletests(p[ok], method="fdr_bh")[1]
        res.loc[idx, "q_within_gene"] = q

    # Save full clean table
    res_sorted = res.sort_values(["q_within_gene", "p_interaction"], ascending=[True, True])
    out_all = out_dir / f"b2_pergene_{tag}_all.csv"
    res_sorted.to_csv(out_all, index=False)

    # Significant per-gene FDR
    sig = res_sorted[res_sorted["q_within_gene"] < q_gene_thr].copy()
    out_sig = out_dir / f"b2_pergene_{tag}_significant_qgene{q_gene_thr:g}.csv"
    sig.to_csv(out_sig, index=False)

    # Per-gene summary (best region per gene)
    summary_rows = []
    for gene, sub in res_sorted.groupby("gene"):
        best = sub.iloc[0]
        summary_rows.append({
            "contrast": tag,
            "gene": gene,
            "best_region": best["region"],
            "beta_interaction": best["beta_interaction"],
            "p_interaction": best["p_interaction"],
            "q_within_gene": best["q_within_gene"],
            "r2": best["r2"],
            "N": best["N"],
            "n_regions_tested": int(len(sub)),
            "n_sig_qgene": int((sub["q_within_gene"] < q_gene_thr).sum())
        })
    summ = pd.DataFrame(summary_rows).sort_values(["n_sig_qgene", "q_within_gene"], ascending=[False, True])
    out_summ = out_dir / f"b2_pergene_{tag}_per_gene_summary.csv"
    summ.to_csv(out_summ, index=False)

    print(f"[DONE] {tag}: models={len(res)} | sig(q_within_gene<{q_gene_thr})={len(sig)}")
    print(f"       wrote: {out_all.name}, {out_sig.name}, {out_summ.name}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", type=str, default=".")
    ap.add_argument("--input-results-dir", type=str, default="results_b2")
    ap.add_argument("--output-dir", type=str, default="results_b2_optionB_pergeneFDR")
    ap.add_argument("--min-per-group", type=int, default=5)
    ap.add_argument("--min-total", type=int, default=25)
    ap.add_argument("--min-nonnull-region", type=int, default=25)
    ap.add_argument("--cov-type", type=str, default="HC3")
    ap.add_argument("--q-gene-thr", type=float, default=0.05)
    args = ap.parse_args()

    data_dir = Path(args.data_dir).expanduser().resolve()
    in_dir = data_dir / args.input_results_dir
    out_dir = data_dir / args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "AsymAD_vs_TypAD": in_dir / "prepared_expr_mri_merged_with_selected_genes_AsymAD_vs_TypAD.csv",
        "AsymAD_vs_Control": in_dir / "prepared_expr_mri_merged_with_selected_genes_AsymAD_vs_Control.csv",
        "TypAD_vs_Control": in_dir / "prepared_expr_mri_merged_with_selected_genes_TypAD_vs_Control.csv",
    }

    for tag, fp in files.items():
        if not fp.exists():
            raise FileNotFoundError(f"Missing prepared file: {fp}")
        df = pd.read_csv(fp)
        run_contrast(
            df=df, tag=tag, out_dir=out_dir,
            min_per_group=args.min_per_group,
            min_total=args.min_total,
            min_nonnull_region=args.min_nonnull_region,
            cov_type=args.cov_type,
            q_gene_thr=args.q_gene_thr
        )


if __name__ == "__main__":
    main()

